example_homepage_name:
    path:     /in/example/whoami/{name}
    defaults: { _controller: ExampleBundle:Example:index }

example_calendar:
    path:     /in/example/calendar
    defaults: { _controller: ExampleBundle:Example:calendar }



