example_homepage:
    path:     /in/example/whoami/{name}
    defaults: { _controller: ExampleBundle:Default:index }

example_calendar:
    path:     /in/example/calendar
    defaults: { _controller: ExampleBundle:Default:calendar}



