toolbox:
    resource: "@ToolboxBundle/Resources/config/routing.yml"
    prefix:   /

mark:
    resource: "@MarkBundle/Resources/config/routing.yml"
    prefix:   /

example:
    resource: "@ExampleBundle/Resources/config/routing.yml"
    prefix:   /

education_calendar:
    resource: "@EducationCalendarBundle/Resources/config/routing.yml"
    prefix:   /

class:
    resource: "@SubjectBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
