start:
    path:     /in
    defaults:
        _controller:  FrameworkBundle:Redirect:redirect
        route:        education_calendar_overview
        permanent:    true

education_calendar_select:
    path:     /in/select
    defaults: { _controller: EducationCalendarBundle:Calendar:select }

education_calendar_overview:
    path:     /in/calendar
    defaults: { _controller: EducationCalendarBundle:Calendar:calendar }