education_calendar_homepage:
    path:     /in/{name}
    defaults: { _controller: EducationCalendarBundle:Default:index }

end_route:
    path:     /in
    defaults: { _controller: EducationCalendarBundle:Default:end }