education_calendar_homepage:
    path:     /hello/{name}
    defaults: { _controller: EducationCalendarBundle:Default:index }

end_route:
    path:     /end/
    defaults: { _controller: EducationCalendarBundle:Default:end }