start:
    path:     /in
    defaults:
        _controller:  FrameworkBundle:Redirect:redirect
        route:        education_calendar_overview
        permanent:    true

education_calendar_overview:
    path:     /in/calendar
    defaults: { _controller: EducationCalendarBundle:Calendar:calendar }