start:
    path:     /in
    defaults:
        _controller:  FrameworkBundle:Redirect:redirect
        route:        education_calendar_overview
        permanent:    true

education_calendar_overview:
    path:     /in/calendar
    defaults: { _controller: EducationCalendarBundle:Calendar:calendar }

education_calendar_accordion_response:
    path:     /in/calendar/accordion/{time}
    defaults: { _controller: EducationCalendarBundle:Calendar:getAccordionResponse }


teaching_unit_save:
    path:     /in/calendar/save/{subject}/{block}/{time}
    defaults: { _controller: EducationCalendarBundle:TeachingUnit:saveTeachingUnit }

teaching_unit_remove:
    path:     /in/calendar/remove/{block}/{time}
    defaults: { _controller: EducationCalendarBundle:TeachingUnit:removeTeachingUnit }