education_calendar_homepage:
    path:     /in/{name}
    defaults: { _controller: EducationCalendarBundle:Default:index }

education_calendar_select:
    path:     /in/select
    defaults: { _controller: EducationCalendarBundle:Default:select }

end_route:
    path:     /in
    defaults: { _controller: EducationCalendarBundle:Default:end }