services:
    teaching_unit_repository:
        class: EducationCalendarBundle\Entity\Repository\TeachingUnitRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments:
            - EducationCalendarBundle\Entity\TeachingUnitEntity