subject_class_new:
    path:     /in/subject/class/new
    defaults: { _controller: SubjectBundle:Subject:new }

subject_select_class:
    path:     /in/select
    defaults: { _controller: SubjectBundle:EducationClass:select }

student_save:
    path:     /in/student/save/{student}
    defaults: { _controller: SubjectBundle:Student:save }

student_new:
    path:     /in/student/new/{subject}
    defaults: { _controller: SubjectBundle:Student:new }

education_class:
    path:     /in/classes
    defaults: { _controller: SubjectBundle:EducationClass:index }